version: "3.9"

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      # note that "postgres" has to match the name of the postgres container
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/docker_demo_db"
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
      SPRING_LOGGING_LEVEL_ROOT: INFO
    depends_on:
      - postgres
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgres
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: docker_demo_db
    restart: always
    networks:
      - backend  

volumes:
  dbdata: 

networks:
  backend:
  frontend: