version: "3.9"

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      # note that "postgres" has to match the name of the postgres container
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/docker_demo_db"
      DB_USERNAME: example_user
      DB_PASSWORD: password123
    depends_on:
      - mysql
    restart: always

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_demo_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: 