version: "3.9"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://mysql-db/docker_demo_db
      DB_USERNAME: example_user
      DB_PASSWORD: password123
    depends_on:
      - mysql-container
    restart: always
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - server
    restart: always
  mysql-container:
    image: mysql:8.0.28
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_demo_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123
    restart: always

volumes:
  dbdata: